from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parent
SRC_PATH = PROJECT_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from journal_recommender import DatasetConfig, JournalRecommendationPipeline, RecommenderConfig


st.set_page_config(
    page_title="CS Journal Recommender",
    page_icon="📚",
    layout="wide",
)

st.markdown(
    """
    <style>
    .stApp {
        background:
            radial-gradient(circle at top left, rgba(15, 118, 110, 0.12), transparent 35%),
            radial-gradient(circle at top right, rgba(29, 78, 216, 0.10), transparent 30%),
            linear-gradient(180deg, #f8fafc 0%, #eef2ff 100%);
        font-family: Georgia, "Times New Roman", serif;
    }
    .hero {
        padding: 1.4rem 1.6rem;
        border-radius: 18px;
        background: rgba(255, 255, 255, 0.85);
        border: 1px solid rgba(15, 23, 42, 0.08);
        box-shadow: 0 18px 50px rgba(15, 23, 42, 0.06);
        margin-bottom: 1rem;
    }
    .result-card {
        padding: 1rem 1.1rem;
        border-radius: 16px;
        background: rgba(255, 255, 255, 0.92);
        border: 1px solid rgba(15, 23, 42, 0.08);
        box-shadow: 0 10px 30px rgba(15, 23, 42, 0.05);
        margin-bottom: 0.9rem;
    }
    .metric-chip {
        display: inline-block;
        padding: 0.25rem 0.55rem;
        border-radius: 999px;
        background: #ecfeff;
        color: #155e75;
        font-size: 0.9rem;
        margin-right: 0.5rem;
        margin-bottom: 0.4rem;
    }
    </style>
    """,
    unsafe_allow_html=True,
)


@st.cache_resource(show_spinner="Building recommendation assets. First run may take a few minutes.")
def load_pipeline() -> JournalRecommendationPipeline:
    config = RecommenderConfig(
        dataset_config=DatasetConfig(profile="assignment_aligned"),
    )
    return JournalRecommendationPipeline(config).build(use_cache=True, include_evaluation=False)


def render_results(results: pd.DataFrame) -> None:
    if results.empty:
        st.warning("No recommendations were generated for the provided abstract.")
        return

    for rank, row in results.iterrows():
        st.markdown(
            f"""
            <div class="result-card">
                <h3 style="margin-bottom:0.3rem;">#{rank + 1} {row['journal_name']}</h3>
                <div class="metric-chip">Score: {row['score_percent']:.2f}%</div>
                <div class="metric-chip">Confidence: {row['confidence_label']}</div>
                <div class="metric-chip">Cluster: {row['cluster_label']}</div>
                <p style="margin-top:0.8rem; margin-bottom:0.6rem;">{row['explanation']}</p>
            </div>
            """,
            unsafe_allow_html=True,
        )
        col1, col2 = st.columns(2)
        with col1:
            st.caption("Overlapping keywords")
            st.write(row["overlapping_keywords"] or ["No direct keyword overlap extracted"])
        with col2:
            st.caption("Overlapping subjects")
            st.write(row["overlapping_subjects"] or ["No direct subject overlap extracted"])
        with st.expander("Supporting similar articles"):
            support = pd.DataFrame(row["supporting_articles"])
            if not support.empty:
                support["score"] = support["score"].map(lambda value: f"{value:.4f}")
            st.dataframe(support, use_container_width=True, hide_index=True)


pipeline = load_pipeline()
summary = pipeline.dataset_summary()

st.markdown(
    f"""
    <div class="hero">
        <h1 style="margin-bottom:0.25rem;">Computer Science Journal Recommendation System</h1>
        <p style="margin-bottom:0.7rem;">
            Enter an academic abstract to retrieve the top 5 most relevant journals, with supporting articles,
            similarity-based explanations, and cluster context.
        </p>
        <div class="metric-chip">Profile: Assignment-aligned</div>
        <div class="metric-chip">Articles: {summary['records']}</div>
        <div class="metric-chip">Journals: {summary['journals']}</div>
        <div class="metric-chip">Years: {summary['year_range'][0]}-{summary['year_range'][1]}</div>
    </div>
    """,
    unsafe_allow_html=True,
)

with st.sidebar:
    st.header("Model")
    model_name = st.selectbox(
        "Recommendation strategy",
        options=["TF-IDF", "BERT", "Hybrid", "Ensemble"],
        index=2,
    )
    st.caption("Hybrid uses 0.6 similarity + 0.2 keyword overlap + 0.2 subject overlap.")
    st.divider()
    st.subheader("Dataset Notes")
    st.write(
        "The SQLite file is larger than the assignment PDF specification, so the app uses the reproducible "
        "assignment-aligned subset generated by the project pipeline."
    )


left, right = st.columns([1.35, 0.85])

with left:
    abstract_input = st.text_area(
        "Article abstract",
        height=280,
        placeholder=(
            "Paste an abstract here. The system will recommend the five most relevant journals "
            "and show why they were selected."
        ),
    )
    run_clicked = st.button("Recommend Journals", type="primary", use_container_width=True)

with right:
    st.subheader("Demo Abstract")
    st.write(
        "Distributed data processing is becoming a reality. Businesses want to stay competitive while integrating "
        "heterogeneous systems, reducing communication costs, and exploiting caching, replication, and parallelism "
        "in distributed database environments."
    )
    st.subheader("Top Journals in the Training Profile")
    st.dataframe(
        pd.DataFrame(summary["top_journals"].items(), columns=["Journal", "Article Count"]),
        use_container_width=True,
        hide_index=True,
    )


if run_clicked:
    if not abstract_input.strip():
        st.warning("Enter an abstract before running the recommender.")
    else:
        with st.spinner("Scoring journals against the article corpus..."):
            if model_name == "TF-IDF":
                results = pipeline.recommend_journals_tfidf(abstract_input)
            elif model_name == "BERT":
                results = pipeline.recommend_journals_bert(abstract_input)
            elif model_name == "Hybrid":
                results = pipeline.recommend_journals_hybrid(abstract_input)
            else:
                results = pipeline.recommend_journals_ensemble(abstract_input)
        st.subheader("Recommendations")
        render_results(results)
